### ISSUE TITLE
Highjacking back button on login screen

### ISSUE THREAD

**Issue by camray** [bigardone/phoenix-toggl#2]
I just popped open [the demo](https://phoenix-toggl.herokuapp.com/sign_in), and tried to go back in my browser. Looks like something is highjacking the back button and making it a bit difficult to go to the last page.

**Comment by bigardone** [comment]
Hi @camray can you give some more info please? I'm trying to reproduce the the issue but the back button works perfectly for me :(

**Comment by camray** [comment]
I'm on Mac OS X 10.10.5 using Chrome 48.0. 
When I press back, it goes back to a phoenix-toggl page, but then forwards me to another. There is a console log that appears every time I press back and appears as follows:
```
action @@router/UPDATE_LOCATION @ 19:00:05.809
action @@router/UPDATE_LOCATION @ 19:00:05.826
```
Hopefully this helps!
